### ISSUE TITLE
Add timer to logging context

### ISSUE THREAD

**Issue by dirkdev98** [lightbasenl/logger#2]
It may be interesting to add the duration in milliseconds between Logger creation and log function calls.

Usecases:

- Background jobs (how long are they running, how long did it take before reaching a certain state)
- Server ( Duration would start on logger creation in the middleware )

At the moment to check this, you would have to manually add `{duration: Date.now() - start }` to all log method calls.

**Comment by dirkdev98** [comment]
Not that useful, all log rows already have a timestamp so time in between can be calculated later, when processing the logs

**Comment by tomasfrancisco** [comment]
Although, the time between requests is different than the time elapsed from the beginning and end of the request. Might still be interesting to have it, if request time becomes an issue, making it easier to debug.
